config/routes.rb
Rails.application.routes.draw do
  get 'landings/index'

  resources :events

  resources :bracket_groups

  resources :brackets

  resources :bowlers

  resources :entries

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]

  root 'landings#index'

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/bracket.rb
class Bracket < ActiveRecord::Base
  belongs_to :bracket_group
  has_and_belongs_to_many :bowlers
end

app/controllers/brackets_controller.rb
class BracketsController < ApplicationController
  before_action :set_bracket, only: [:show, :edit, :update, :destroy]

  # GET /brackets
  # GET /brackets.json
  def index
    @brackets = Bracket.all
  end

  # GET /brackets/1
  # GET /brackets/1.json
  def show
  end

  # GET /brackets/new
  def new
    @bracket = Bracket.new
  end

  # GET /brackets/1/edit
  def edit
  end

  # POST /brackets
  # POST /brackets.json
  def create
    @bracket = Bracket.new(bracket_params)

    respond_to do |format|
      if @bracket.save
        format.html { redirect_to @bracket, notice: 'Bracket was successfully created.' }
        format.json { render :show, status: :created, location: @bracket }
      else
        format.html { render :new }
        format.json { render json: @bracket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /brackets/1
  # PATCH/PUT /brackets/1.json
  def update
    respond_to do |format|
      if @bracket.update(bracket_params)
        format.html { redirect_to @bracket, notice: 'Bracket was successfully updated.' }
        format.json { render :show, status: :ok, location: @bracket }
      else
        format.html { render :edit }
        format.json { render json: @bracket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /brackets/1
  # DELETE /brackets/1.json
  def destroy
    @bracket.destroy
    respond_to do |format|
      format.html { redirect_to brackets_url, notice: 'Bracket was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bracket
      @bracket = Bracket.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bracket_params
      params.require(:bracket).permit(:bracket_group_id, :seeds, :results)
    end
end

app/helpers/brackets_helper.rb
module BracketsHelper
end

app/views/brackets/_form.html.erb
<%= form_for @bracket, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :seeds, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :seeds, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :results, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :results, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  brackets_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/brackets/edit.html.erb
<%- model_class = Bracket -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => Bracket %></h1>
</div>
<%= render :partial => 'form' %>

app/views/brackets/index.html.erb
<%- model_class = Bracket -%>
<div class="page-header">
  <h1><%=t '.title', :default => Bracket %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:seeds) %></th>
      <th><%= model_class.human_attribute_name(:results) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @brackets.each do |bracket| %>
      <tr>
        <td><%= bracket.id %></td>
        <td><%= bracket.seeds %></td>
        <td><%= bracket.results %></td>
        <td><%=l bracket.created_at, format: :long %></td>
        <td>
          <%= link_to bracket_path(bracket), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to bracket_path(bracket), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_bracket_path,
            :class => 'btn btn-primary' %>

app/views/brackets/new.html.erb
<%- model_class = Bracket -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => Bracket %></h1>
</div>
<%= render :partial => 'form' %>

app/views/brackets/show.html.erb
<%- model_class = Bracket -%>
<div class="page-header">
  <h1><%=t '.title', :default => Bracket %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:seeds) %></dt>
      <dd><pre class="prettyprint"><%= @bracket.seeds %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:results) %></dt>
      <dd><pre class="prettyprint"><%= @bracket.results %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              brackets_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_bracket_path(@bracket), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              bracket_path(@bracket),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>