config/routes.rb
Rails.application.routes.draw do
  get 'landings/index'

  resources :events

  resources :bracket_groups

  resources :brackets

  resources :bowlers

  resources :entries

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]

  root 'landings#index'

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/bowler.rb
class Bowler < ActiveRecord::Base
  has_many :entries
  has_and_belongs_to_many :brackets
end

app/controllers/bowlers_controller.rb
class BowlersController < ApplicationController
  before_action :set_bowler, only: [:show, :edit, :update, :destroy]

  # GET /bowlers
  # GET /bowlers.json
  def index
    @bowlers = Bowler.all
  end

  # GET /bowlers/1
  # GET /bowlers/1.json
  def show
  end

  # GET /bowlers/new
  def new
    @bowler = Bowler.new
  end

  # GET /bowlers/1/edit
  def edit
  end

  # POST /bowlers
  # POST /bowlers.json
  def create
    @bowler = Bowler.new(bowler_params)

    respond_to do |format|
      if @bowler.save
        format.html { redirect_to @bowler, notice: 'Bowler was successfully created.' }
        format.json { render :show, status: :created, location: @bowler }
      else
        format.html { render :new }
        format.json { render json: @bowler.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bowlers/1
  # PATCH/PUT /bowlers/1.json
  def update
    respond_to do |format|
      if @bowler.update(bowler_params)
        format.html { redirect_to @bowler, notice: 'Bowler was successfully updated.' }
        format.json { render :show, status: :ok, location: @bowler }
      else
        format.html { render :edit }
        format.json { render json: @bowler.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bowlers/1
  # DELETE /bowlers/1.json
  def destroy
    @bowler.destroy
    respond_to do |format|
      format.html { redirect_to bowlers_url, notice: 'Bowler was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bowler
      @bowler = Bowler.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bowler_params
      params.require(:bowler).permit(:starting_lane)
    end
end

app/helpers/bowlers_helper.rb
module BowlersHelper
end

app/views/bowlers/_form.html.erb
<%= form_for @bowler, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :starting_lane, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.number_field :starting_lane, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  bowlers_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/bowlers/edit.html.erb
<%- model_class = Bowler -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => Bowler %></h1>
</div>
<%= render :partial => 'form' %>

app/views/bowlers/index.html.erb
<%- model_class = Bowler -%>
<div class="page-header">
  <h1><%=t '.title', :default => Bowler %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:starting_lane) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @bowlers.each do |bowler| %>
      <tr>
        <td><%= bowler.id %></td>
        <td><%= bowler.starting_lane %></td>
        <td><%=l bowler.created_at, format: :long %></td>
        <td>
          <%= link_to bowler_path(bowler), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to bowler_path(bowler), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_bowler_path,
            :class => 'btn btn-primary' %>

app/views/bowlers/new.html.erb
<%- model_class = Bowler -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => Bowler %></h1>
</div>
<%= render :partial => 'form' %>

app/views/bowlers/show.html.erb
<%- model_class = Bowler -%>
<div class="page-header">
  <h1><%=t '.title', :default => Bowler %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:starting_lane) %></dt>
      <dd><pre class="prettyprint"><%= @bowler.starting_lane %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              bowlers_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_bowler_path(@bowler), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              bowler_path(@bowler),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>