config/routes.rb
Rails.application.routes.draw do
  get 'landings/index'

  resources :events

  resources :bracket_groups

  resources :brackets

  resources :bowlers

  resources :entries

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]

  root 'landings#index'

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/bracket_group.rb
class BracketGroup < ActiveRecord::Base
  belongs_to :event
  has_many :brackets
end

app/controllers/bracket_groups_controller.rb
class BracketGroupsController < ApplicationController
  before_action :set_bracket_group, only: [:show, :edit, :update, :destroy]

  # GET /bracket_groups
  # GET /bracket_groups.json
  def index
    @bracket_groups = BracketGroup.all
  end

  # GET /bracket_groups/1
  # GET /bracket_groups/1.json
  def show
  end

  # GET /bracket_groups/new
  def new
    @bracket_group = BracketGroup.new
  end

  # GET /bracket_groups/1/edit
  def edit
  end

  # POST /bracket_groups
  # POST /bracket_groups.json
  def create
    @bracket_group = BracketGroup.new(bracket_group_params)

    respond_to do |format|
      if @bracket_group.save
        format.html { redirect_to @bracket_group, notice: 'Bracket group was successfully created.' }
        format.json { render :show, status: :created, location: @bracket_group }
      else
        format.html { render :new }
        format.json { render json: @bracket_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bracket_groups/1
  # PATCH/PUT /bracket_groups/1.json
  def update
    respond_to do |format|
      if @bracket_group.update(bracket_group_params)
        format.html { redirect_to @bracket_group, notice: 'Bracket group was successfully updated.' }
        format.json { render :show, status: :ok, location: @bracket_group }
      else
        format.html { render :edit }
        format.json { render json: @bracket_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bracket_groups/1
  # DELETE /bracket_groups/1.json
  def destroy
    @bracket_group.destroy
    respond_to do |format|
      format.html { redirect_to bracket_groups_url, notice: 'Bracket group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bracket_group
      @bracket_group = BracketGroup.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bracket_group_params
      params.require(:bracket_group).permit(:name, :event_id)
    end
end

app/helpers/bracket_groups_helper.rb
module BracketGroupsHelper
end

app/views/bracket_groups/_form.html.erb
<%= form_for @bracket_group, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :name, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  bracket_groups_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/bracket_groups/edit.html.erb
<%- model_class = BracketGroup -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => BracketGroup %></h1>
</div>
<%= render :partial => 'form' %>

app/views/bracket_groups/index.html.erb
<%- model_class = BracketGroup -%>
<div class="page-header">
  <h1><%=t '.title', :default => BracketGroup %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @bracket_groups.each do |bracket_group| %>
      <tr>
        <td><%= bracket_group.id %></td>
        <td><%= bracket_group.name %></td>
        <td><%=l bracket_group.created_at, format: :long %></td>
        <td>
          <%= link_to bracket_group_path(bracket_group), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to bracket_group_path(bracket_group), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_bracket_group_path,
            :class => 'btn btn-primary' %>

app/views/bracket_groups/new.html.erb
<%- model_class = BracketGroup -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => BracketGroup %></h1>
</div>
<%= render :partial => 'form' %>

app/views/bracket_groups/show.html.erb
<%- model_class = BracketGroup -%>
<div class="page-header">
  <h1><%=t '.title', :default => BracketGroup %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:name) %></dt>
      <dd><pre class="prettyprint"><%= @bracket_group.name %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              bracket_groups_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_bracket_group_path(@bracket_group), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              bracket_group_path(@bracket_group),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>